import type { CategoryKey } from '../types'

// ── Specs affichées sur les cartes du configurateur (par catégorie) ──────────

export const KEY_SPECS: Record<CategoryKey, string[]> = {
  cpu:         ['socket', 'total_cores', 'threads', 'perf_boost_clock'],
  motherboard: ['socket', 'form_factor', 'ram_type', 'memory_slots'],
  ram:         ['ram_type', 'speed_mhz', 'modules_quantity', 'module_capacity_gb'],
  gpu:         ['memory_gb', 'memory_type', 'core_boost_clock', 'tdp'],
  storage:     ['capacity_gb', 'storage_type', 'interface', 'nvme'],
  psu:         ['wattage', 'efficiency_rating', 'modular'],
  pc_case:     ['form_factor', 'side_panel', 'max_gpu_length_mm'],
  cpu_cooler:  ['water_cooled', 'max_fan_rpm', 'max_noise_db', 'cpu_sockets'],
}

// ── Labels lisibles pour les clés de specs ───────────────────────────────────

export const SPEC_LABELS: Record<string, string> = {
  // ── Processeur ─────────────────────────────────────────────────────────────
  socket:                    'Socket',
  microarchitecture:         'Microarchitecture',
  core_family:               'Famille de processeurs',
  total_cores:               'Nombre de cœurs',
  performance_cores:         'Cœurs performance',
  efficiency_cores:          'Cœurs efficacité',
  threads:                   'Nombre de threads',
  perf_base_clock:           'Fréquence de base',
  perf_boost_clock:          'Fréquence boost',
  eff_base_clock:            'Fréquence de base (E-cores)',
  eff_boost_clock:           'Fréquence boost (E-cores)',
  l1_cache:                  'Cache L1',
  l2_cache_mb:               'Cache L2',
  l3_cache_mb:               'Cache L3',
  tdp:                       'Consommation (TDP)',
  ppt:                       'Puissance totale (PPT)',
  integrated_graphics:       'Graphiques intégrés',
  igpu_base_clock:           'Fréquence iGPU de base',
  igpu_boost_clock:          'Fréquence iGPU boost',
  ecc_support:               'Support mémoire ECC',
  includes_cooler:           'Ventirad inclus',
  packaging:                 'Conditionnement',
  lithography:               'Finesse de gravure',
  smt:                       'Multi-threading (SMT / HT)',
  max_memory_gb:             'RAM maximale supportée',
  memory_types:              'Types de RAM supportés',
  memory_channels:           'Canaux mémoire',

  // ── Carte mère ─────────────────────────────────────────────────────────────
  form_factor:               'Format',
  chipset:                   'Chipset',
  ram_type:                  'Type de RAM supporté',
  memory_slots:              'Nombre de slots RAM',
  pcie_slots:                'Slots PCIe',
  m2_slots:                  'Slots M.2',
  sata_6gbs:                 'Ports SATA 6 Gb/s',
  sata_3gbs:                 'Ports SATA 3 Gb/s',
  u2:                        'Connecteur U.2',
  wireless_networking:       'Wi-Fi / Bluetooth',
  onboard_ethernet:          'Ethernet intégré',
  usb_headers:               'Connecteurs USB internes',
  audio_chipset:             'Chipset audio',
  audio_channels:            'Canaux audio',
  raid_support:              'Support RAID',
  back_panel_ports:          'Ports panneau arrière',
  ecc:                       'Support ECC',

  // ── RAM ────────────────────────────────────────────────────────────────────
  speed_mhz:                 'Fréquence',
  modules_quantity:          'Nombre de modules',
  module_capacity_gb:        'Capacité par module',
  total_capacity_gb:         'Capacité totale',
  cas_latency:               'Latence CAS',
  timings:                   'Timings',
  voltage:                   'Tension',
  registered:                'Registered (RDIMM)',
  heat_spreader:             'Dissipateur thermique',
  rgb:                       'Éclairage RGB',
  height_mm:                 'Hauteur',
  profile_support:           'Profils supportés (XMP / EXPO)',

  // ── Carte graphique ────────────────────────────────────────────────────────
  chipset_manufacturer:      'Fabricant du chipset',
  core_count:                'Nombre de cœurs GPU',
  memory_gb:                 'Mémoire vidéo',
  memory_type:               'Type de mémoire vidéo',
  core_base_clock:           'Fréquence de base GPU',
  core_boost_clock:          'Fréquence boost GPU',
  effective_memory_clock:    'Fréquence mémoire effective',
  memory_bus:                'Bus mémoire',
  interface:                 'Interface',
  frame_sync:                'Synchronisation d\'image',
  length_mm:                 'Longueur',
  case_expansion_slot_width: 'Largeur (slots boîtier)',
  total_slot_width:          'Largeur totale',
  cooling:                   'Refroidissement',
  pcie_6_pin:                'Connecteurs PCIe 6 broches',
  pcie_8_pin:                'Connecteurs PCIe 8 broches',
  pcie_12vhpwr:              'Connecteur 12VHPWR',
  pcie_12v_2x6:              'Connecteur 12V-2x6',
  hdmi_2_1:                  'Sorties HDMI 2.1',
  hdmi_2_0:                  'Sorties HDMI 2.0',
  displayport_2_1:           'Sorties DisplayPort 2.1',
  displayport_1_4a:          'Sorties DisplayPort 1.4a',
  dvi_d:                     'Sorties DVI-D',
  vga:                       'Sorties VGA',

  // ── Stockage ───────────────────────────────────────────────────────────────
  capacity_gb:               'Capacité',
  storage_type:              'Type de stockage',
  nvme:                      'NVMe',
  cache_mb:                  'Cache',

  // ── Alimentation ───────────────────────────────────────────────────────────
  wattage:                   'Puissance',
  efficiency_rating:         'Certification efficacité',
  modular:                   'Câblage modulaire',
  fanless:                   'Sans ventilateur',
  atx_24_pin:                'Connecteur ATX 24 broches',
  eps_8_pin:                 'Connecteurs EPS 8 broches',
  pcie_6_plus_2_pin:         'Connecteurs PCIe 6+2 broches',
  sata:                      'Connecteurs SATA',
  molex_4_pin:               'Connecteurs Molex 4 broches',

  // ── Boîtier ────────────────────────────────────────────────────────────────
  supported_mobo_form_factors: 'Formats de carte mère supportés',
  side_panel:                'Panneau latéral',
  psu_included:              'Alimentation incluse',
  supported_psu_form_factors: 'Formats d\'alimentation supportés',
  max_gpu_length_mm:         'Longueur GPU max.',
  max_cpu_cooler_height_mm:  'Hauteur ventirad max.',
  internal_35_bays:          'Baies internes 3,5"',
  internal_25_bays:          'Baies internes 2,5"',
  external_35_bays:          'Baies externes 3,5"',
  external_525_bays:         'Baies externes 5,25"',
  expansion_slots:           'Slots d\'extension',
  front_usb_ports:           'Ports USB façade',
  depth_mm:                  'Profondeur',
  width_mm:                  'Largeur',
  volume_liters:             'Volume',
  weight_lbs:                'Poids',

  // ── Ventirad ───────────────────────────────────────────────────────────────
  min_fan_rpm:               'Vitesse ventilateur min.',
  max_fan_rpm:               'Vitesse ventilateur max.',
  min_noise_db:              'Niveau sonore min.',
  max_noise_db:              'Niveau sonore max.',
  cpu_sockets:               'Sockets compatibles',
  water_cooled:              'Watercooling',
  radiator_size_mm:          'Taille du radiateur',
  fan_size_mm:               'Diamètre du ventilateur',
  fan_quantity:              'Nombre de ventilateurs',
}

// ── Unités affichées après les valeurs de specs ───────────────────────────────

export const SPEC_UNITS: Partial<Record<string, string>> = {
  // Fréquences
  perf_base_clock:         'GHz',
  perf_boost_clock:        'GHz',
  eff_base_clock:          'GHz',
  eff_boost_clock:         'GHz',
  igpu_base_clock:         'MHz',
  igpu_boost_clock:        'MHz',
  core_base_clock:         'MHz',
  core_boost_clock:        'MHz',
  effective_memory_clock:  'MHz',
  speed_mhz:               'MHz',
  // Mémoire
  memory_gb:               'Go',
  module_capacity_gb:      'Go',
  total_capacity_gb:       'Go',
  max_memory_gb:           'Go',
  l2_cache_mb:             'Mo',
  l3_cache_mb:             'Mo',
  cache_mb:                'Mo',
  memory_bus:              'bits',
  // Stockage
  capacity_gb:             'Go',
  // Consommation
  tdp:                     'W',
  ppt:                     'W',
  wattage:                 'W',
  voltage:                 'V',
  // Dimensions
  length_mm:               'mm',
  height_mm:               'mm',
  depth_mm:                'mm',
  width_mm:                'mm',
  max_gpu_length_mm:       'mm',
  max_cpu_cooler_height_mm:'mm',
  radiator_size_mm:        'mm',
  fan_size_mm:             'mm',
  // Ventilateurs
  min_fan_rpm:             'tr/min',
  max_fan_rpm:             'tr/min',
  min_noise_db:            'dB',
  max_noise_db:            'dB',
  // Boîtier
  volume_liters:           'L',
  weight_lbs:              'lbs',
  // Alimentation
  pcie_6_plus_2_pin:       'x',
  pcie_8_pin:              'x',
  pcie_6_pin:              'x',
  eps_8_pin:               'x',
  sata:                    'x',
  molex_4_pin:             'x',
}
