const { createContext, useContext } = React

const RouterCtx = createContext({ page: 'home', params: {}, navigate: () => {} })
window.RouterCtx = RouterCtx

const CATEGORIES = [
  { value: 'cpu',        label: 'Processeur',      icon: '⚡', color: '#3B82F6', bg: 'rgba(59,130,246,0.1)',   count: '2 400+' },
  { value: 'gpu',        label: 'Carte graphique',  icon: '🎮', color: '#EF4444', bg: 'rgba(239,68,68,0.1)',    count: '1 800+' },
  { value: 'motherboard',label: 'Carte mère',       icon: '🔌', color: '#6366F1', bg: 'rgba(99,102,241,0.1)',   count: '3 200+' },
  { value: 'ram',        label: 'Mémoire RAM',      icon: '💾', color: '#22C55E', bg: 'rgba(34,197,94,0.1)',    count: '5 600+' },
  { value: 'storage',    label: 'Stockage',         icon: '💿', color: '#F59E0B', bg: 'rgba(245,158,11,0.1)',   count: '4 100+' },
  { value: 'psu',        label: 'Alimentation',     icon: '🔋', color: '#EC4899', bg: 'rgba(236,72,153,0.1)',   count: '1 200+' },
  { value: 'pc_case',    label: 'Boîtier',          icon: '🖥️', color: '#14B8A6', bg: 'rgba(20,184,166,0.1)',   count: '2 800+' },
  { value: 'cpu_cooler', label: 'Ventirad',         icon: '❄️', color: '#8B5CF6', bg: 'rgba(139,92,246,0.1)',   count: '3 500+' },
]
window.CATEGORIES = CATEGORIES

const MOCK_PRODUCTS = {
  cpu: [
    { id:'cpu-1', name:'AMD Ryzen 9 7950X', manufacturer:'AMD', series:'Ryzen 9', release_year:2022,
      price_min_eur:449, price_max_eur:549, price_avg_eur:499, benchmark_score:62400,
      image_url:null, description:'Le processeur haut de gamme AMD pour le workstation et gaming. 16 cœurs Zen 4.',
      specs:{ cores:16, threads:32, boost_clock:'5.7 GHz', base_clock:'4.5 GHz', tdp:'170W', socket:'AM5', cache:'64 MB L3' }},
    { id:'cpu-2', name:'Intel Core i9-14900K', manufacturer:'Intel', series:'Core i9', release_year:2023,
      price_min_eur:399, price_max_eur:489, price_avg_eur:444, benchmark_score:59200,
      image_url:null, description:'Le flagship Intel avec 24 cœurs hybrides pour des performances maximales.',
      specs:{ cores:24, threads:32, boost_clock:'6.0 GHz', base_clock:'3.2 GHz', tdp:'253W', socket:'LGA1700', cache:'36 MB L3' }},
    { id:'cpu-3', name:'AMD Ryzen 7 7800X3D', manufacturer:'AMD', series:'Ryzen 7', release_year:2023,
      price_min_eur:329, price_max_eur:399, price_avg_eur:364, benchmark_score:48600,
      image_url:null, description:'Le meilleur CPU gaming grâce à la technologie 3D V-Cache. Performances exceptionnelles.',
      specs:{ cores:8, threads:16, boost_clock:'5.0 GHz', base_clock:'4.2 GHz', tdp:'120W', socket:'AM5', cache:'96 MB L3' }},
    { id:'cpu-4', name:'Intel Core i7-14700K', manufacturer:'Intel', series:'Core i7', release_year:2023,
      price_min_eur:289, price_max_eur:349, price_avg_eur:319, benchmark_score:44200,
      image_url:null, description:'20 cœurs haute performance avec une fréquence boost impressionnante.',
      specs:{ cores:20, threads:28, boost_clock:'5.6 GHz', base_clock:'3.4 GHz', tdp:'253W', socket:'LGA1700', cache:'33 MB L3' }},
    { id:'cpu-5', name:'AMD Ryzen 5 7600X', manufacturer:'AMD', series:'Ryzen 5', release_year:2022,
      price_min_eur:179, price_max_eur:229, price_avg_eur:204, benchmark_score:33800,
      image_url:null, description:'Le rapport performance/prix imbattable pour les builds milieu de gamme.',
      specs:{ cores:6, threads:12, boost_clock:'5.3 GHz', base_clock:'4.7 GHz', tdp:'105W', socket:'AM5', cache:'32 MB L3' }},
    { id:'cpu-6', name:'Intel Core i5-14600K', manufacturer:'Intel', series:'Core i5', release_year:2023,
      price_min_eur:219, price_max_eur:269, price_avg_eur:244, benchmark_score:35600,
      image_url:null, description:'14 cœurs hybrides pour un excellent équilibre entre gaming et productivité.',
      specs:{ cores:14, threads:20, boost_clock:'5.3 GHz', base_clock:'3.5 GHz', tdp:'181W', socket:'LGA1700', cache:'24 MB L3' }},
  ],
  gpu: [
    { id:'gpu-1', name:'NVIDIA RTX 4090', manufacturer:'NVIDIA', series:'RTX 40', release_year:2022,
      price_min_eur:999, price_max_eur:1399, price_avg_eur:1199, benchmark_score:86200,
      image_url:null, description:'La carte graphique ultime. 16 384 CUDA cores, DLSS 3, ray tracing de nouvelle génération.',
      specs:{ vram:'24 GB GDDR6X', tdp:'450W', interface:'PCIe 4.0 x16', cuda_cores:'16 384', boost_clock:'2.52 GHz' }},
    { id:'gpu-2', name:'NVIDIA RTX 4080 Super', manufacturer:'NVIDIA', series:'RTX 40', release_year:2024,
      price_min_eur:799, price_max_eur:999, price_avg_eur:899, benchmark_score:72400,
      image_url:null, description:'Performances 4K fluides avec 16 GB GDDR6X. Le sweet spot haut de gamme.',
      specs:{ vram:'16 GB GDDR6X', tdp:'320W', interface:'PCIe 4.0 x16', cuda_cores:'10 240', boost_clock:'2.55 GHz' }},
    { id:'gpu-3', name:'AMD Radeon RX 7900 XTX', manufacturer:'AMD', series:'RX 7000', release_year:2022,
      price_min_eur:699, price_max_eur:899, price_avg_eur:799, benchmark_score:68600,
      image_url:null, description:'24 GB GDDR6, parfait pour la création de contenu 3D et le gaming en 4K.',
      specs:{ vram:'24 GB GDDR6', tdp:'355W', interface:'PCIe 4.0 x16', stream_processors:'12 288', boost_clock:'2.5 GHz' }},
    { id:'gpu-4', name:'NVIDIA RTX 4070 Ti Super', manufacturer:'NVIDIA', series:'RTX 40', release_year:2024,
      price_min_eur:599, price_max_eur:749, price_avg_eur:674, benchmark_score:61200,
      image_url:null, description:'16 GB GDDR6X pour un gaming en 1440p ultra et 4K confortable.',
      specs:{ vram:'16 GB GDDR6X', tdp:'285W', interface:'PCIe 4.0 x16', cuda_cores:'8 448', boost_clock:'2.61 GHz' }},
    { id:'gpu-5', name:'AMD Radeon RX 7800 XT', manufacturer:'AMD', series:'RX 7000', release_year:2023,
      price_min_eur:399, price_max_eur:499, price_avg_eur:449, benchmark_score:48200,
      image_url:null, description:'Le choix idéal pour le 1440p gaming à un prix compétitif.',
      specs:{ vram:'16 GB GDDR6', tdp:'263W', interface:'PCIe 4.0 x16', stream_processors:'3 840', boost_clock:'2.43 GHz' }},
    { id:'gpu-6', name:'NVIDIA RTX 4070 Super', manufacturer:'NVIDIA', series:'RTX 40', release_year:2024,
      price_min_eur:499, price_max_eur:599, price_avg_eur:549, benchmark_score:54600,
      image_url:null, description:'DLSS 3 Frame Generation, 12 GB GDDR6X — le meilleur rapport qualité/prix.',
      specs:{ vram:'12 GB GDDR6X', tdp:'220W', interface:'PCIe 4.0 x16', cuda_cores:'7 168', boost_clock:'2.48 GHz' }},
  ],
  motherboard: [
    { id:'mb-1', name:'ASUS ROG Crosshair X670E Hero', manufacturer:'ASUS', series:'ROG Crosshair', release_year:2022,
      price_min_eur:549, price_max_eur:649, price_avg_eur:599, benchmark_score:null,
      image_url:null, description:'La référence pour plateforme AM5 haut de gamme. VRM 18+2 phases, PCIe 5.0.',
      specs:{ socket:'AM5', form_factor:'ATX', chipset:'X670E', ddr:'DDR5', m2_slots:4, usb_ports:'USB 4.0 Gen3' }},
    { id:'mb-2', name:'MSI MEG Z790 ACE', manufacturer:'MSI', series:'MEG', release_year:2022,
      price_min_eur:499, price_max_eur:599, price_avg_eur:549, benchmark_score:null,
      image_url:null, description:'Plateforme Z790 premium avec Wi-Fi 6E et Thunderbolt 4.',
      specs:{ socket:'LGA1700', form_factor:'ATX', chipset:'Z790', ddr:'DDR5', m2_slots:5, usb_ports:'Thunderbolt 4' }},
    { id:'mb-3', name:'Gigabyte B650 AORUS Elite AX', manufacturer:'Gigabyte', series:'AORUS', release_year:2022,
      price_min_eur:199, price_max_eur:249, price_avg_eur:224, benchmark_score:null,
      image_url:null, description:'Le meilleur rapport qualité/prix pour plateforme AM5 en DDR5.',
      specs:{ socket:'AM5', form_factor:'ATX', chipset:'B650', ddr:'DDR5', m2_slots:2, usb_ports:'USB 3.2 Gen2' }},
  ],
  ram: [
    { id:'ram-1', name:"G.Skill Trident Z5 RGB 32 GB", manufacturer:'G.Skill', series:'Trident Z5', release_year:2022,
      price_min_eur:89, price_max_eur:129, price_avg_eur:109, benchmark_score:null,
      image_url:null, description:'DDR5-6400 CL32 — RGB haut de gamme pour les passionnés.',
      specs:{ capacity:'32 GB', speed:'DDR5-6400', latency:'CL32', voltage:'1.4V', rgb:'Oui' }},
    { id:'ram-2', name:'Corsair Dominator Platinum 64 GB', manufacturer:'Corsair', series:'Dominator Platinum', release_year:2022,
      price_min_eur:199, price_max_eur:259, price_avg_eur:229, benchmark_score:null,
      image_url:null, description:'64 GB DDR5-5600 avec iCUE RGB. Le must-have pour les workstations.',
      specs:{ capacity:'64 GB', speed:'DDR5-5600', latency:'CL36', voltage:'1.25V', rgb:'Oui' }},
    { id:'ram-3', name:'Kingston Fury Beast 32 GB', manufacturer:'Kingston', series:'Fury Beast', release_year:2022,
      price_min_eur:69, price_max_eur:99, price_avg_eur:84, benchmark_score:null,
      image_url:null, description:'DDR5-5200 sans RGB — performances solides sans fioritures.',
      specs:{ capacity:'32 GB', speed:'DDR5-5200', latency:'CL40', voltage:'1.1V', rgb:'Non' }},
  ],
  storage: [
    { id:'st-1', name:'Samsung 990 Pro 2 TB', manufacturer:'Samsung', series:'990 Pro', release_year:2022,
      price_min_eur:119, price_max_eur:159, price_avg_eur:139, benchmark_score:null,
      image_url:null, description:'Le NVMe PCIe 4.0 de référence. 7450 Mo/s en lecture, ultra fiable.',
      specs:{ capacity:'2 TB', interface:'PCIe 4.0 NVMe', seq_read:'7 450 Mo/s', seq_write:'6 900 Mo/s', form_factor:'M.2 2280' }},
    { id:'st-2', name:'WD Black SN850X 1 TB', manufacturer:'WD', series:'Black SN850X', release_year:2022,
      price_min_eur:79, price_max_eur:109, price_avg_eur:94, benchmark_score:null,
      image_url:null, description:'Optimisé gaming, conçu avec Microsoft pour Xbox. Latences réduites.',
      specs:{ capacity:'1 TB', interface:'PCIe 4.0 NVMe', seq_read:'7 300 Mo/s', seq_write:'6 300 Mo/s', form_factor:'M.2 2280' }},
    { id:'st-3', name:'Seagate FireCuda 530 4 TB', manufacturer:'Seagate', series:'FireCuda 530', release_year:2021,
      price_min_eur:259, price_max_eur:329, price_avg_eur:294, benchmark_score:null,
      image_url:null, description:'4 TB PCIe 4.0 avec heatsink intégré. Idéal pour les gros stocks de jeux.',
      specs:{ capacity:'4 TB', interface:'PCIe 4.0 NVMe', seq_read:'7 300 Mo/s', seq_write:'6 900 Mo/s', form_factor:'M.2 2280' }},
  ],
  psu: [
    { id:'psu-1', name:'Corsair RM1000x 1000W', manufacturer:'Corsair', series:'RMx', release_year:2021,
      price_min_eur:149, price_max_eur:189, price_avg_eur:169, benchmark_score:null,
      image_url:null, description:'1000W 80+ Gold, ventilateur semi-passif, entièrement modulaire.',
      specs:{ wattage:'1 000W', rating:'80+ Gold', modular:'Full', fan:'135 mm semi-passif', warranty:'10 ans' }},
    { id:'psu-2', name:'NZXT C850 Gold 850W', manufacturer:'NZXT', series:'C Gold', release_year:2022,
      price_min_eur:119, price_max_eur:149, price_avg_eur:134, benchmark_score:null,
      image_url:null, description:'850W compact et silencieux. Certifié 80+ Gold, câbles individuels.',
      specs:{ wattage:'850W', rating:'80+ Gold', modular:'Full', fan:'120 mm', warranty:'7 ans' }},
    { id:'psu-3', name:'Seasonic Focus GX-750', manufacturer:'Seasonic', series:'Focus GX', release_year:2020,
      price_min_eur:99, price_max_eur:129, price_avg_eur:114, benchmark_score:null,
      image_url:null, description:'La référence 80+ Gold de Seasonic. Fiabilité légendaire.',
      specs:{ wattage:'750W', rating:'80+ Gold', modular:'Full', fan:'120 mm hybride', warranty:'10 ans' }},
  ],
  pc_case: [
    { id:'case-1', name:'Fractal Design Torrent', manufacturer:'Fractal Design', series:'Torrent', release_year:2021,
      price_min_eur:149, price_max_eur:189, price_avg_eur:169, benchmark_score:null,
      image_url:null, description:'Airflow exceptionnel grâce à la façade mesh. Design épuré scandinave.',
      specs:{ form_factor:'ATX', window:'Tempered Glass', fans_included:'2x 180mm + 3x 140mm', max_gpu_length:'461 mm' }},
    { id:'case-2', name:'Lian Li O11 Dynamic EVO', manufacturer:'Lian Li', series:'O11 Dynamic', release_year:2021,
      price_min_eur:139, price_max_eur:169, price_avg_eur:154, benchmark_score:null,
      image_url:null, description:'Le boîtier de référence pour watercooling custom. Double vitrage.',
      specs:{ form_factor:'ATX', window:'Tempered Glass (x2)', fans_included:'Aucun', max_gpu_length:'420 mm' }},
    { id:'case-3', name:'NZXT H9 Elite', manufacturer:'NZXT', series:'H9', release_year:2023,
      price_min_eur:229, price_max_eur:279, price_avg_eur:254, benchmark_score:null,
      image_url:null, description:'Le summum du design premium avec chambre de câbles exposée.',
      specs:{ form_factor:'ATX', window:'Tempered Glass panoramique', fans_included:'3x 120mm', max_gpu_length:'435 mm' }},
  ],
  cpu_cooler: [
    { id:'cool-1', name:'Noctua NH-D15', manufacturer:'Noctua', series:'NH-D15', release_year:2014,
      price_min_eur:89, price_max_eur:109, price_avg_eur:99, benchmark_score:null,
      image_url:null, description:'Le meilleur ventirad aircooling au monde. Silencieux et ultra efficace.',
      specs:{ type:'Air', height:'165 mm', fans:'2x NF-A15 140mm', tdp_support:'250W', socket_compat:'AM5 / LGA1700' }},
    { id:'cool-2', name:'Arctic Liquid Freezer III 360', manufacturer:'Arctic', series:'Liquid Freezer III', release_year:2023,
      price_min_eur:89, price_max_eur:119, price_avg_eur:104, benchmark_score:null,
      image_url:null, description:'AIO 360mm au rapport qualité/prix imbattable. 3 fans P12 Max inclus.',
      specs:{ type:'AIO', radiator:'360 mm', fans:'3x 120mm P12 Max', tdp_support:'300W', socket_compat:'AM5 / LGA1700' }},
    { id:'cool-3', name:'Corsair iCUE H150i Elite LCD', manufacturer:'Corsair', series:'iCUE H150i', release_year:2022,
      price_min_eur:149, price_max_eur:189, price_avg_eur:169, benchmark_score:null,
      image_url:null, description:'AIO 360mm avec écran LCD sur la tête de pompe. RGB XT fans.',
      specs:{ type:'AIO', radiator:'360 mm', fans:'3x 120mm RGB XT', tdp_support:'350W', socket_compat:'AM5 / LGA1700' }},
  ],
}
window.MOCK_PRODUCTS = MOCK_PRODUCTS

const KEY_SPECS = {
  cpu: ['cores','threads','boost_clock','socket'],
  gpu: ['vram','tdp','boost_clock'],
  motherboard: ['socket','chipset','ddr','form_factor'],
  ram: ['capacity','speed','latency'],
  storage: ['capacity','interface','seq_read'],
  psu: ['wattage','rating','modular'],
  pc_case: ['form_factor','window','fans_included'],
  cpu_cooler: ['type','radiator','fans'],
}
window.KEY_SPECS = KEY_SPECS

Object.assign(window, { RouterCtx, CATEGORIES, MOCK_PRODUCTS, KEY_SPECS })
